#!/bin/bash

# --- 颜色配置 ---
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

# --- 1. 检查 Root 权限 ---
if [ "$EUID" -ne 0 ]; then
  echo -e "${RED}错误: 请使用 root 权限运行此脚本 (sudo bash bbr.sh)${NC}"
  exit 1
fi

echo -e "${GREEN}=== 开始安装 BBR 及 TCP 网络优化 ===${NC}"

# --- 2. 备份 sysctl.conf ---
BACKUP_FILE="/etc/sysctl.conf.bak.$(date +%F-%H%M)"
cp /etc/sysctl.conf "$BACKUP_FILE"
echo -e "${YELLOW}已备份原配置至: $BACKUP_FILE${NC}"

# --- 3. 清理旧的优化配置 (防止重复添加) ---
# 如果之前运行过此脚本，先删除旧的 "Gemini" 标记块，保持文件整洁
sed -i '/# =.*BBR & TCP 调优完整配置/,/# --- 4. 系统级转发/d' /etc/sysctl.conf
# 删除可能残留的空行（可选，为了美观）
sed -i '/^# =.*BBR & TCP 调优完整配置/d' /etc/sysctl.conf

# --- 4. 写入新的配置 ---
echo -e "${YELLOW}正在写入 TCP 优化参数...${NC}"

cat <<EOF >> /etc/sysctl.conf

# ==========================================
# BBR & TCP 调优完整配置 (Generated by Gemini)
# ==========================================

# --- 1. 开启 BBR 核心 ---
# 指定队列算法为 fq (BBR 必须)
net.core.default_qdisc = fq
# 开启 BBR 拥塞控制
net.ipv4.tcp_congestion_control = bbr

# --- 2. 内存缓冲区优化 (让大宽带跑满) ---
# 接收/发送缓冲区最大值 (32MB)
net.core.rmem_max = 33554432
net.core.wmem_max = 33554432
# TCP 读/写缓冲区 (最小 默认 最大)
net.ipv4.tcp_rmem = 4096 87380 33554432
net.ipv4.tcp_wmem = 4096 16384 33554432
# 开启 TCP 窗口自动缩放
net.ipv4.tcp_window_scaling = 1
# 增加网络设备积压队列 (防止丢包)
net.core.netdev_max_backlog = 5000

# --- 3. 连接与并发优化 (抗高负载) ---
# 增加半连接队列 (防 SYN Flood)
net.ipv4.tcp_max_syn_backlog = 8192
# 开启 TCP Fast Open (3 = 开启发送和接收)
net.ipv4.tcp_fastopen = 3
# 允许重用 TIME_WAIT socket
net.ipv4.tcp_tw_reuse = 1
# 缩短 Keepalive 探测时间 (600秒)
net.ipv4.tcp_keepalive_time = 600
# 减少重试次数
net.ipv4.tcp_synack_retries = 1
net.ipv4.tcp_syn_retries = 1

# --- 4. 系统级转发 (如果跑代理/Docker需要) ---
net.ipv4.ip_forward = 1
EOF

# --- 5. 应用配置 ---
echo -e "${YELLOW}正在应用系统参数 (sysctl -p)...${NC}"
sysctl -p > /dev/null 2>&1

# --- 6. 验证结果 ---
echo -e "\n${GREEN}=== 验证 BBR 状态 ===${NC}"

# 检查拥塞控制算法
CURRENT_ALGO=$(sysctl net.ipv4.tcp_congestion_control | awk '{print $3}')
# 检查队列算法
CURRENT_QDISC=$(sysctl net.core.default_qdisc | awk '{print $3}')

if [[ "$CURRENT_ALGO" == "bbr" && "$CURRENT_QDISC" == "fq" ]]; then
    echo -e "拥塞控制: ${GREEN}$CURRENT_ALGO${NC} (符合预期)"
    echo -e "队列算法: ${GREEN}$CURRENT_QDISC${NC} (符合预期)"
    echo -e "\n${GREEN}✅ BBR 启动成功 & TCP 调优已完成！${NC}"
else
    echo -e "拥塞控制: ${RED}$CURRENT_ALGO${NC}"
    echo -e "队列算法: ${RED}$CURRENT_QDISC${NC}"
    echo -e "\n${RED}❌ 警告: BBR 可能未生效，请检查内核版本是否 >= 4.9${NC}"
fi
